QUESTION 1

In [3]:
import numpy as np

ar=np.array([each for each in range (2,51,3)])
print(ar)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


QUESTION 2

In [6]:
lst1=list(input().split(' '))
lst2=list(input().split(' '))
ar1=np.array(lst1)
ar2=np.array(lst2)
print(np.concatenate((ar1,ar2)))
print(np.sort(np.concatenate((ar1,ar2))))

1 3 5 7 8 
6 1 4 3 0
['1' '3' '5' '7' '8' '' '6' '1' '4' '3' '0']
['' '0' '1' '1' '3' '3' '4' '5' '6' '7' '8']


QUESTION 3

In [7]:
arrr=np.random.rand(3,5)
print(arrr.shape)
print(arrr.size)

(3, 5)
15


QUESTION 4

In [17]:
import numpy as np

ar=np.array([2,1,3])
print(ar.shape)
ar1=ar[np.newaxis].shape
ar2=np.expand_dims(ar,axis=1).shape
print(ar1)
print(ar2)

(3,)
(1, 3)
(3, 1)


QUESTION 5

In [24]:
ar=np.random.rand(3,3)
ar2=np.random.rand(3,3)
print(np.vstack((ar,ar2)),"\n")
print(np.hstack((ar,ar2)))

[[0.32424161 0.33927825 0.44809639]
 [0.83101572 0.80469178 0.94044127]
 [0.80847735 0.62046694 0.5479878 ]
 [0.30164251 0.0033762  0.68267688]
 [0.91123849 0.10642578 0.69599603]
 [0.28455437 0.62357143 0.24802318]] 

[[0.32424161 0.33927825 0.44809639 0.30164251 0.0033762  0.68267688]
 [0.83101572 0.80469178 0.94044127 0.91123849 0.10642578 0.69599603]
 [0.80847735 0.62046694 0.5479878  0.28455437 0.62357143 0.24802318]]


QUESTION 6

In [26]:
ar=np.array([1,2,2,5,4,6,8,9,12,1,1,2,5,6,8,9,8,8,5,2,5,12,45,4,5,121,2,1,6,44,4,64,6,6,6,1,31,61])
unique,occur=np.unique(ar,return_counts=True)
print(unique,"\n",occur)

[  1   2   4   5   6   8   9  12  31  44  45  61  64 121] 
 [5 5 3 5 6 4 2 2 1 1 1 1 1 1]
